# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Payment Pointers
email: adrian@hopebailie.com
twitter_username: ahopebailie
github_username:  adrianhopebailie
description: >- 
  Payment Pointers are a standardized identifier for payment accounts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Just The Docs Config
# https://pmarsceill.github.io/just-the-docs/docs/configuration/

search_enabled: true
# aux_links:
#    "Specification at interledger.org":
#      - "//interledger.org/rfcs/0026-payment-pointers/"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
